print('caso você queira mudar de escala digite (0) para °C')
C = float(input('digite uma temperatura em °C:'))
F = float(1.8*C + 32)
K = float(C + 273)
print('C = {} ,K = {} ,F = {} '.format(C, K, F))
F1 = float(input('digite uma temperatura em °F'))
C1 = float((F1 - 32)/1.8)
K1 = float(C1 + 273)
print('C = {} ,K = {} ,F = {} '.format(C1, K1, F1))
K2 = float(input('digite um temperatura em °K'))
C2 = float(K2 - 273)
F2 = float(((K2 - 273)*(9/5)) - 32)
print('C = {} ,K = {} ,F = {} '.format(C2, K2, F2))
